Feature/forms
phfdonda/re-former pull request #1
Opened 2020-06-05 20:49 UTC by phfdonda

**Hi!**
This is the conclusion of the Re-form project about Form in Rails. We have:
1- Created a new Rails app;
2- Generated a simple User controller, model and view;
3- Applied the new knowledge about "form_for";
4- Created an error message about wrong parameters in forms.
We hope this pull request is of your liking, let us know if we can improve it in any way.
Thank you for your review!

2020-06-06 18:34 UTC, mcrd25 requested changes
# Changes Required 🔍 

Hi Team! 👋 

Good job!

#### Required Changes
- You seem not to have your stickler set up, please do this. See this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/auth/sign-in/?next=/library/fast-track-curriculum/69047/path/step/54883773/)
- You are missing the commented out `form_tag` form as can be seen from this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_tag2.png) from Odin.

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-08 15:32 UTC, phfdonda commented on app/controllers/users_controller.rb
> +
Solved

2020-06-08 15:33 UTC, phfdonda commented on app/models/user.rb
> +class EmailValidator < ActiveModel::EachValidator
Solved

2020-06-08 15:34 UTC, phfdonda commented on app/models/user.rb
> +    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
Solved

2020-06-08 15:35 UTC, phfdonda commented on app/models/user.rb
> +      record.errors[attribute] << (options[:message] || "is not an email")
Solved

2020-06-08 15:37 UTC, phfdonda commented on app/models/user.rb
> +    if value.nil?
Solved

2020-06-08 15:37 UTC, phfdonda commented on app/models/user.rb
> +      record.errors[attribute] << (options[:message] || "value must not be nil")
Solved

2020-06-08 15:38 UTC, phfdonda commented on app/models/user.rb
> +    unless value.split('').none?(/[\W]/)
Solved

2020-06-08 15:38 UTC, phfdonda commented on app/models/user.rb
> +      record.errors[attribute] << (options[:message] || "must be composed of only letters and numbers")
Solved

2020-06-08 15:38 UTC, phfdonda commented on app/models/user.rb
> +
Solved

2020-06-08 15:40 UTC, phfdonda commented on config/routes.rb
> +  resources :users, only: [:new, :create, :edit, :update]
Solved

2020-06-08 15:40 UTC, phfdonda commented on config/routes.rb
> +
Solved

2020-06-08 15:43 UTC, phfdonda commented
Hi!
I solved all errors reported. I didn't get that I should keep the form_tag commented, thanks for pointing that out.
I hope everything's ok now, let me know if there's anything else I should fix.
Thank you for your review!

2020-06-08 18:07 UTC, uryelah commented
Hi **Pedro Donda & J. P. Pérez Tejada Ladrón de Guevara**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job turning on Stickler and bring back the form_tag.

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**


---------

    
    
**Keep being an awesome dev and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-06-08 18:55 UTC, merged